language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install -y qt5-default libqt5webkit5-dev build-essential python-lxml python-pip xvfb
install:
  - pip install .
  - pip install coveralls
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-package=psnstoreprice
after_success:
  - coveralls