language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install -y xvfb
  - Xvfb :1 -screen 0 1024x768x16 -nolisten inet6
  - export DISPLAY=localhost:1.0
install:
  - pip install .
  - pip install coveralls
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-package=psnstoreprice
after_success:
  - coveralls